---
name: AeoliaLib
main: xyz.aeolia.lib.AeoliaLib
version: "%%VERSION"
author: Asheiou
api-version: 1.21.5
softdepend:
- Vault
- LuckPerms
- SmartInvs
depend:
- Essentials
website: https://asheiou.cymru
description: '>
              The Aeolia bespoke everything-plugin!'
commands:
  util:
    aliases: util
    description: Admin command.
    usage: "/<command>"
    permission: lib.admin
    permission-message: You don't have lib.admin.
  broadcast:
    description: Broadcast a message to the server and the Discord.
    usage: "/<command> <message>"
    permission: lib.broadcast
    permission-message: You don't have lib.broadcast.
    aliases:
    - bc
    - shout
  code:
    description: Generate a code to verify you own your account.
    usage: "/<command>"
    permission: lib.code
    permission-message: You don't have lib.code.
  fake:
    description: Fake join or quit
    usage: "/<command> <join/quit> [user]"
    permission: lib.fake
    permission-message: You don't have lib.fake.
  headsell:
    aliases: sellhead
    description: Sell any unwanted player heads back to the server!
    usage: "/<command> <amount/all>"
    permission: lib.headsell
    permission-message: You don't have lib.headsell.
  minimessage:
    description: Send a chat message in MiniMessage
    usage: "/<command> [@Username] <message>"
    permission: lib.minimessage
    permission-message: You don't have lib.minimessage.
    aliases:
    - mm
    - mmsay
  mod:
    description: Toggle mod mode
    usage: "/<command> [true/false/status]"
    permission: lib.mod
    permission-message: You don't have lib.mod.
  pvp:
    description: Pick a kit and play
    usage: "/<command>"
    permission: lib.pvp
    permission-message: You don't have lib.pvp.
  report:
    description: Create a report to our staff
    usage: "/<command> <report message>"
    permission: lib.report
    permission-message: You don't have lib.report.
  suffix:
    description: Open the suffix menu
    usage: "/<command>"
    permission: lib.suffix
    permission-message: You don't have lib.suffix.
  vanishonlogin:
    aliases: vol
    description: Vanish on login
    usage: "/<command> [true/false] [user]"
    permission: lib.vanishonlogin
    permission-message: You don't have lib.vanishonlogin.
  xpbuy:
    aliases: buyxp
    description: Buy XP!
    usage: "/<command> <amount/maximum>"
    permission: lib.xpbuy
    permission-message: You don't have lib.xpbuy.
  xpsell:
    aliases: sellxp
    description: Sell XP for money!
    usage: "/<command> <amount/all>"
    permission: lib.xpsell
    permission-message: You don't have lib.xpsell.

permissions:
  lib.admin:
    description: Allows /util
    default: op
  lib.alert:
    description: Allows seeing alerts
    default: op
  lib.broadcast:
    description: Allows /broadcast
    default: op
  lib.clearchat.exempt:
    description: Allows exemption from /util clearchat
    default: op
  lib.code:
    description: Allows /code
    default: true
  lib.fake:
    description: Allows /fake
    default: op
  lib.headsell:
    description: Allows head sell
    default: true
  lib.lockchat.exempt:
    description: Allows exemption from /util lockchat
    default: op
  lib.minimessage:
    description: Allows /minimessage
    default: op
  lib.mod:
    description: Allows mod mode
    default: op
  lib.pvp:
    description: Allows /pvp
    default: true
  lib.report:
    description: Allows /report
    default: true
  lib.suffix:
    description: Allows /suffix
    default: true
  lib.suffix-grant:
    description: Allows /suffix with arguments
    default: op
  lib.vanishonlogin:
    description: Allows use of /vanishonlogin for this user
    default: op
  lib.vanishonlogin.others:
    description: Allows use of /vanishonlogin for all users
    default: op
  lib.xpbuy:
    description: Allows /xpbuy
    default: true
  lib.xpsell:
    description: Allows /xpsell
    default: true
