name: AshUtils
main: xyz.aeolia.ashutils.AshUtils
version: ${project.version}
author: Asheiou
api-version: 1.21.5
softdepend: [ Vault, LuckPerms, SmartInvs ]
depend: [ Essentials ]
website: https://asheiou.cymru
description: >
             The Aeolia bespoke everything-plugin!
commands:
  broadcast:
    description: Broadcast a message to the server and the Discord.
    usage: /<command> <message>
    permission: ashutils.broadcast
    permission-message: You don't have ashutils.broadcast.
    aliases: [bc, shout]
  code:
    description: Generate a code to verify you own your account.
    usage: /<command>
    permission: ashutils.code
    permission-message: You don't have ashutils.code.
  headsell:
    aliases: sellhead
    description: Sell any unwanted player heads back to the server!
    usage: /<command> <amount/all>
    permission: ashutils.headsell
    permission-message: You don't have ashutils.headsell.
  ashutils:
    aliases: util
    description: Admin command.
    usage: /<command>
    permission: ashutils.admin
    permission-message: You don't have ashutils.admin.
  fake:
    description: Fake join or quit
    usage: /<command> <join/quit> [user]
    permission: ashutils.fake
    permission-message: You don't have ashutils.fake.
  minimessage:
    description: Send a chat message in MiniMessage
    usage: /<command> [@Username] <message>
    permission: ashutils.minimessage
    permission-message: You don't have ashutils.minimessage.
    aliases: [mm, mmsay]
  mod:
    description: Toggle mod mode
    usage: /<command> [true/false/status]
    permission: ashutils.mod
    permission-message: You don't have ashutils.mod.
  report:
    description: Create a report to our staff
    usage: /<command> <report message>
    permission: ashutils.report
    permission-message: You don't have ashutils.report.
  vanishonlogin:
    aliases: vol
    description: Vanish on login
    usage: /<command> [true/false] [user]
    permission: ashutils.vanishonlogin
    permission-message: You don't have ashutils.vanishonlogin.
  xpsell:
    aliases: sellxp
    description: Sell XP for money!
    usage: /<command> <amount/all>
    permission: ashutils.xpsell
    permission-message: You don't have ashutils.xpsell.
  xpbuy:
    aliases: buyxp
    description: Buy XP!
    usage: /<command> <amount/maximum>
    permission: ashutils.xpbuy
    permission-message: You don't have ashutils.xpbuy.
  suffix:
    description: Open the suffix menu
    usage: /<command>
    permission: ashutils.suffix
    permission-message: You don't have ashutils.suffix.
    

permissions:
  ashutils.alert:
    description: Allows seeing alerts
    default: op
  ashutils.broadcast:
    description: Allows /broadcast
    default: op
  ashutils.code:
    description: Allows /code
    default: true
  ashutils.admin:
    description: Allows /ashutils
    default: op
  ashutils.fake:
    description: Allows /fake
    default: op
  ashutils.minimessage:
    description: Allows /minimessage
    default: op
  ashutils.mod:
    description: Allows mod mode
    default: op
  ashutils.report:
    description: Allows /report
    default: true
  ashutils.xpsell:
    description: Allows /xpsell
    default: true
  ashutils.suffix:
    description: Allows /suffix
    default: true
  ashutils.suffix-grant:
    description: Allows /suffix with arguments
    default: op
  ashutils.xpbuy:
    description: Allows /xpbuy
    default: true
  ashutils.lockchat.exempt:
    description: Allows exemption from /ashutils lockchat
    default: op
  ashutils.clearchat.exempt:
    description: Allows exemption from /ashutils clearchat
    default: op
  ashutils.vanishonlogin:
    description: Allows use of /vanishonlogin for this user
    default: op
  ashutils.vanishonlogin.others:
    description: Allows use of /vanishonlogin for all users
    default: op
  ashutils.headsell:
    description: Allows head sell
    default: true
